//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using BookStoreMVC.Infrastructures;
    
    public partial class Book
    {
        public Book()
        {
            this.Orders = new HashSet<Order>();
            this.Authors = new HashSet<Author>();
        }
    
        //Validation using Metadata
        [Required]
        //[DuplicateId(ErrorMessage = "Duplicate Id not allowed")]
        [Display(Name = "Book ID")]
        public int BookId { get; set; }

        [Required]
        public string Title { get; set; }

        public string Description { get; set; }

        [Required]
        public Nullable<int> Price { get; set; }

        [StringLength(8, MinimumLength =3)]
        public string ISBN { get; set; }

        //Custom property Validation
        [Display(Name = "Publication Date")]
        [DataType(DataType.Date)]        
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [NotFutureDate(ErrorMessage = "Publication Date cann't be in Future")]
        public Nullable<System.DateTime> PublicationDate { get; set; }

        [Display(Name = "Category ID")]
        public Nullable<int> CategoryId { get; set; }

        [Display(Name = "Publisher ID")]
        public Nullable<int> PublisherId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
    }
}
