//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book1
    {
        public int BookId { get; set; }
        public int BookPrice { get; set; }
        public int BookISBN { get; set; }
        public string BookTitle { get; set; }
        public int BookCategoryId { get; set; }
        public string CategoryId { get; set; }
        public int PublisherId { get; set; }
        public string BookDescription { get; set; }
        public System.DateTime PublicationDate { get; set; }
    }
}
